###########################
## Markdown Linter rules ##
###########################

# Linter rules doc:
# - https://github.com/DavidAnson/markdownlint
#
# Note:
# To comment out a single error:
#   <!-- markdownlint-disable -->
#   any violations you want
#   <!-- markdownlint-restore -->
#

###############
# Rules by id #
###############
MD001: false                  # Header increment - callouts break rule
MD004: false                  # Unordered list style
MD007:
  indent: 2                   # Unordered list indentation
MD009: true                   # no trailing spaces
MD013:
  line_length: 400            # Line length 80 is far to short
MD026:
  punctuation: ".,;:!。，；:"  # List of not allowed
MD029: false                  # Ordered list item prefix
MD033: false                  # No inline HTML
MD034: false                  # no bare urls
MD036: false                  # Emphasis used instead of a heading
MD041: false                  # first line heading should be top level heading

#################
# Rules by tags #
#################
blank_lines: false  # Error on blank lines
