############################################
## Super Linter GitHub Actions            ##
##                                        ##
## Link code and documentation            ##
## https://github.com/github/super-linter ##
############################################

name: "Super Linter"

on:
  pull_request:
  push:
    branches:
    - live
    paths-ignore:
      - '.github/**'

jobs:
  build:
    name: Container
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint everything
        uses: github/super-linter/slim@v4
        env:
          ## Define Linters to run (others set to false)
          VALIDATE_YAML: true
          VALIDATE_MARKDOWN: true
          VALIDATE_CLOJURE: true
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: live
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_INCLUDE: .*/.*
